"""add accepted column to invites

Revision ID: f23386ef4c21
Revises: 4c8f9a5082c1
Create Date: 2025-05-08 22:48:39.089731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23386ef4c21'
down_revision: Union[str, None] = '4c8f9a5082c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'accepted')
    # ### end Alembic commands ###
